/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivationTopkByTokenPost200ResponseResultsInner } from './ActivationTopkByTokenPost200ResponseResultsInner';
import {
    ActivationTopkByTokenPost200ResponseResultsInnerFromJSON,
    ActivationTopkByTokenPost200ResponseResultsInnerFromJSONTyped,
    ActivationTopkByTokenPost200ResponseResultsInnerToJSON,
    ActivationTopkByTokenPost200ResponseResultsInnerToJSONTyped,
} from './ActivationTopkByTokenPost200ResponseResultsInner';

/**
 * Response for NPActivationTopkByTokenRequest.
 * @export
 * @interface ActivationTopkByTokenPost200Response
 */
export interface ActivationTopkByTokenPost200Response {
    /**
     * 
     * @type {Array<ActivationTopkByTokenPost200ResponseResultsInner>}
     * @memberof ActivationTopkByTokenPost200Response
     */
    results: Array<ActivationTopkByTokenPost200ResponseResultsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivationTopkByTokenPost200Response
     */
    tokens: Array<string>;
}

/**
 * Check if a given object implements the ActivationTopkByTokenPost200Response interface.
 */
export function instanceOfActivationTopkByTokenPost200Response(value: object): value is ActivationTopkByTokenPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function ActivationTopkByTokenPost200ResponseFromJSON(json: any): ActivationTopkByTokenPost200Response {
    return ActivationTopkByTokenPost200ResponseFromJSONTyped(json, false);
}

export function ActivationTopkByTokenPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationTopkByTokenPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ActivationTopkByTokenPost200ResponseResultsInnerFromJSON)),
        'tokens': json['tokens'],
    };
}

export function ActivationTopkByTokenPost200ResponseToJSON(json: any): ActivationTopkByTokenPost200Response {
    return ActivationTopkByTokenPost200ResponseToJSONTyped(json, false);
}

export function ActivationTopkByTokenPost200ResponseToJSONTyped(value?: ActivationTopkByTokenPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ActivationTopkByTokenPost200ResponseResultsInnerToJSON)),
        'tokens': value['tokens'],
    };
}

