/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivationSinglePost200ResponseActivation } from './ActivationSinglePost200ResponseActivation';
import {
    ActivationSinglePost200ResponseActivationFromJSON,
    ActivationSinglePost200ResponseActivationFromJSONTyped,
    ActivationSinglePost200ResponseActivationToJSON,
    ActivationSinglePost200ResponseActivationToJSONTyped,
} from './ActivationSinglePost200ResponseActivation';

/**
 * Response for NPActivationSingleRequest. Contains the activation values and tokenized prompt.
 * @export
 * @interface ActivationSinglePost200Response
 */
export interface ActivationSinglePost200Response {
    /**
     * 
     * @type {ActivationSinglePost200ResponseActivation}
     * @memberof ActivationSinglePost200Response
     */
    activation: ActivationSinglePost200ResponseActivation;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivationSinglePost200Response
     */
    tokens: Array<string>;
}

/**
 * Check if a given object implements the ActivationSinglePost200Response interface.
 */
export function instanceOfActivationSinglePost200Response(value: object): value is ActivationSinglePost200Response {
    if (!('activation' in value) || value['activation'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    return true;
}

export function ActivationSinglePost200ResponseFromJSON(json: any): ActivationSinglePost200Response {
    return ActivationSinglePost200ResponseFromJSONTyped(json, false);
}

export function ActivationSinglePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationSinglePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'activation': ActivationSinglePost200ResponseActivationFromJSON(json['activation']),
        'tokens': json['tokens'],
    };
}

export function ActivationSinglePost200ResponseToJSON(json: any): ActivationSinglePost200Response {
    return ActivationSinglePost200ResponseToJSONTyped(json, false);
}

export function ActivationSinglePost200ResponseToJSONTyped(value?: ActivationSinglePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activation': ActivationSinglePost200ResponseActivationToJSON(value['activation']),
        'tokens': value['tokens'],
    };
}

