/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One feature and its activation in an NPActivationAllResponse
 * @export
 * @interface ActivationAllPost200ResponseActivationsInner
 */
export interface ActivationAllPost200ResponseActivationsInner {
    /**
     * 
     * @type {string}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    index: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    values: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    sumValues?: number;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    maxValue: number;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    maxValueIndex: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    dfaValues?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    dfaTargetIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ActivationAllPost200ResponseActivationsInner
     */
    dfaMaxValue?: number;
}

/**
 * Check if a given object implements the ActivationAllPost200ResponseActivationsInner interface.
 */
export function instanceOfActivationAllPost200ResponseActivationsInner(value: object): value is ActivationAllPost200ResponseActivationsInner {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('maxValue' in value) || value['maxValue'] === undefined) return false;
    if (!('maxValueIndex' in value) || value['maxValueIndex'] === undefined) return false;
    return true;
}

export function ActivationAllPost200ResponseActivationsInnerFromJSON(json: any): ActivationAllPost200ResponseActivationsInner {
    return ActivationAllPost200ResponseActivationsInnerFromJSONTyped(json, false);
}

export function ActivationAllPost200ResponseActivationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationAllPost200ResponseActivationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'index': json['index'],
        'values': json['values'],
        'sumValues': json['sum_values'] == null ? undefined : json['sum_values'],
        'maxValue': json['max_value'],
        'maxValueIndex': json['max_value_index'],
        'dfaValues': json['dfa_values'] == null ? undefined : json['dfa_values'],
        'dfaTargetIndex': json['dfa_target_index'] == null ? undefined : json['dfa_target_index'],
        'dfaMaxValue': json['dfa_max_value'] == null ? undefined : json['dfa_max_value'],
    };
}

export function ActivationAllPost200ResponseActivationsInnerToJSON(json: any): ActivationAllPost200ResponseActivationsInner {
    return ActivationAllPost200ResponseActivationsInnerToJSONTyped(json, false);
}

export function ActivationAllPost200ResponseActivationsInnerToJSONTyped(value?: ActivationAllPost200ResponseActivationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'index': value['index'],
        'values': value['values'],
        'sum_values': value['sumValues'],
        'max_value': value['maxValue'],
        'max_value_index': value['maxValueIndex'],
        'dfa_values': value['dfaValues'],
        'dfa_target_index': value['dfaTargetIndex'],
        'dfa_max_value': value['dfaMaxValue'],
    };
}

