/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner
 */
export interface ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner {
    /**
     * The index of the feature in the SAE.
     * @type {number}
     * @memberof ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner
     */
    featureIndex: number;
    /**
     * The activation value of this feature at this token position.
     * @type {number}
     * @memberof ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner
     */
    activationValue: number;
}

/**
 * Check if a given object implements the ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner interface.
 */
export function instanceOfActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner(value: object): value is ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner {
    if (!('featureIndex' in value) || value['featureIndex'] === undefined) return false;
    if (!('activationValue' in value) || value['activationValue'] === undefined) return false;
    return true;
}

export function ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerFromJSON(json: any): ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner {
    return ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerFromJSONTyped(json, false);
}

export function ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'featureIndex': json['feature_index'],
        'activationValue': json['activation_value'],
    };
}

export function ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerToJSON(json: any): ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner {
    return ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerToJSONTyped(json, false);
}

export function ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInnerToJSONTyped(value?: ActivationTopkByTokenPost200ResponseResultsInnerTopFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feature_index': value['featureIndex'],
        'activation_value': value['activationValue'],
    };
}

