/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A feature in Neuronpedia, identified by model, source, and index.
 * @export
 * @interface NPFeature
 */
export interface NPFeature {
    /**
     * 
     * @type {string}
     * @memberof NPFeature
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof NPFeature
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof NPFeature
     */
    index: number;
}

/**
 * Check if a given object implements the NPFeature interface.
 */
export function instanceOfNPFeature(value: object): value is NPFeature {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function NPFeatureFromJSON(json: any): NPFeature {
    return NPFeatureFromJSONTyped(json, false);
}

export function NPFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): NPFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'source': json['source'],
        'index': json['index'],
    };
}

export function NPFeatureToJSON(json: any): NPFeature {
    return NPFeatureToJSONTyped(json, false);
}

export function NPFeatureToJSONTyped(value?: NPFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'source': value['source'],
        'index': value['index'],
    };
}

