/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NPSteerType = {
    Steered: 'STEERED',
    Default: 'DEFAULT'
} as const;
export type NPSteerType = typeof NPSteerType[keyof typeof NPSteerType];


export function instanceOfNPSteerType(value: any): boolean {
    for (const key in NPSteerType) {
        if (Object.prototype.hasOwnProperty.call(NPSteerType, key)) {
            if (NPSteerType[key as keyof typeof NPSteerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NPSteerTypeFromJSON(json: any): NPSteerType {
    return NPSteerTypeFromJSONTyped(json, false);
}

export function NPSteerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NPSteerType {
    return json as NPSteerType;
}

export function NPSteerTypeToJSON(value?: NPSteerType | null): any {
    return value as any;
}

export function NPSteerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NPSteerType {
    return value as NPSteerType;
}

