/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NPSteerChatResult } from './NPSteerChatResult';
import {
    NPSteerChatResultFromJSON,
    NPSteerChatResultFromJSONTyped,
    NPSteerChatResultToJSON,
    NPSteerChatResultToJSONTyped,
} from './NPSteerChatResult';

/**
 * The steering/default chat responses.
 * @export
 * @interface SteerCompletionChatPost200Response
 */
export interface SteerCompletionChatPost200Response {
    /**
     * 
     * @type {Array<NPSteerChatResult>}
     * @memberof SteerCompletionChatPost200Response
     */
    outputs: Array<NPSteerChatResult>;
    /**
     * 
     * @type {NPSteerChatResult}
     * @memberof SteerCompletionChatPost200Response
     */
    input: NPSteerChatResult;
}

/**
 * Check if a given object implements the SteerCompletionChatPost200Response interface.
 */
export function instanceOfSteerCompletionChatPost200Response(value: object): value is SteerCompletionChatPost200Response {
    if (!('outputs' in value) || value['outputs'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function SteerCompletionChatPost200ResponseFromJSON(json: any): SteerCompletionChatPost200Response {
    return SteerCompletionChatPost200ResponseFromJSONTyped(json, false);
}

export function SteerCompletionChatPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SteerCompletionChatPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'outputs': ((json['outputs'] as Array<any>).map(NPSteerChatResultFromJSON)),
        'input': NPSteerChatResultFromJSON(json['input']),
    };
}

export function SteerCompletionChatPost200ResponseToJSON(json: any): SteerCompletionChatPost200Response {
    return SteerCompletionChatPost200ResponseToJSONTyped(json, false);
}

export function SteerCompletionChatPost200ResponseToJSONTyped(value?: SteerCompletionChatPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outputs': ((value['outputs'] as Array<any>).map(NPSteerChatResultToJSON)),
        'input': NPSteerChatResultToJSON(value['input']),
    };
}

