/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NPFeature } from './NPFeature';
import {
    NPFeatureFromJSON,
    NPFeatureFromJSONTyped,
    NPFeatureToJSON,
    NPFeatureToJSONTyped,
} from './NPFeature';
import type { UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner } from './UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner';
import {
    UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSON,
    UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSONTyped,
    UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSON,
    UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSONTyped,
} from './UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner';

/**
 * 
 * @export
 * @interface UtilSaeTopkByDecoderCossimPost200Response
 */
export interface UtilSaeTopkByDecoderCossimPost200Response {
    /**
     * 
     * @type {NPFeature}
     * @memberof UtilSaeTopkByDecoderCossimPost200Response
     */
    feature?: NPFeature;
    /**
     * 
     * @type {Array<UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner>}
     * @memberof UtilSaeTopkByDecoderCossimPost200Response
     */
    topkDecoderCossimFeatures?: Array<UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner>;
}

/**
 * Check if a given object implements the UtilSaeTopkByDecoderCossimPost200Response interface.
 */
export function instanceOfUtilSaeTopkByDecoderCossimPost200Response(value: object): value is UtilSaeTopkByDecoderCossimPost200Response {
    return true;
}

export function UtilSaeTopkByDecoderCossimPost200ResponseFromJSON(json: any): UtilSaeTopkByDecoderCossimPost200Response {
    return UtilSaeTopkByDecoderCossimPost200ResponseFromJSONTyped(json, false);
}

export function UtilSaeTopkByDecoderCossimPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtilSaeTopkByDecoderCossimPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'feature': json['feature'] == null ? undefined : NPFeatureFromJSON(json['feature']),
        'topkDecoderCossimFeatures': json['topk_decoder_cossim_features'] == null ? undefined : ((json['topk_decoder_cossim_features'] as Array<any>).map(UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSON)),
    };
}

export function UtilSaeTopkByDecoderCossimPost200ResponseToJSON(json: any): UtilSaeTopkByDecoderCossimPost200Response {
    return UtilSaeTopkByDecoderCossimPost200ResponseToJSONTyped(json, false);
}

export function UtilSaeTopkByDecoderCossimPost200ResponseToJSONTyped(value?: UtilSaeTopkByDecoderCossimPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feature': NPFeatureToJSON(value['feature']),
        'topk_decoder_cossim_features': value['topkDecoderCossimFeatures'] == null ? undefined : ((value['topkDecoderCossimFeatures'] as Array<any>).map(UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSON)),
    };
}

