/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UtilSaeVectorPost200Response
 */
export interface UtilSaeVectorPost200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof UtilSaeVectorPost200Response
     */
    vector: Array<number>;
}

/**
 * Check if a given object implements the UtilSaeVectorPost200Response interface.
 */
export function instanceOfUtilSaeVectorPost200Response(value: object): value is UtilSaeVectorPost200Response {
    if (!('vector' in value) || value['vector'] === undefined) return false;
    return true;
}

export function UtilSaeVectorPost200ResponseFromJSON(json: any): UtilSaeVectorPost200Response {
    return UtilSaeVectorPost200ResponseFromJSONTyped(json, false);
}

export function UtilSaeVectorPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtilSaeVectorPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'vector': json['vector'],
    };
}

export function UtilSaeVectorPost200ResponseToJSON(json: any): UtilSaeVectorPost200Response {
    return UtilSaeVectorPost200ResponseToJSONTyped(json, false);
}

export function UtilSaeVectorPost200ResponseToJSONTyped(value?: UtilSaeVectorPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector': value['vector'],
    };
}

