/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NPFeature } from './NPFeature';
import {
    NPFeatureFromJSON,
    NPFeatureFromJSONTyped,
    NPFeatureToJSON,
    NPFeatureToJSONTyped,
} from './NPFeature';

/**
 * 
 * @export
 * @interface UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner
 */
export interface UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner {
    /**
     * 
     * @type {NPFeature}
     * @memberof UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner
     */
    feature?: NPFeature;
    /**
     * 
     * @type {number}
     * @memberof UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner
     */
    cosineSimilarity?: number;
}

/**
 * Check if a given object implements the UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner interface.
 */
export function instanceOfUtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner(value: object): value is UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner {
    return true;
}

export function UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSON(json: any): UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner {
    return UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSONTyped(json, false);
}

export function UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'feature': json['feature'] == null ? undefined : NPFeatureFromJSON(json['feature']),
        'cosineSimilarity': json['cosine_similarity'] == null ? undefined : json['cosine_similarity'],
    };
}

export function UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSON(json: any): UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner {
    return UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSONTyped(json, false);
}

export function UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInnerToJSONTyped(value?: UtilSaeTopkByDecoderCossimPost200ResponseTopkDecoderCossimFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feature': NPFeatureToJSON(value['feature']),
        'cosine_similarity': value['cosineSimilarity'],
    };
}

