/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - AutoInterp Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExplainDefaultPost200Response
 */
export interface ExplainDefaultPost200Response {
    /**
     * The generated explanation for the given set of activations
     * @type {string}
     * @memberof ExplainDefaultPost200Response
     */
    explanation: string;
}

/**
 * Check if a given object implements the ExplainDefaultPost200Response interface.
 */
export function instanceOfExplainDefaultPost200Response(value: object): value is ExplainDefaultPost200Response {
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    return true;
}

export function ExplainDefaultPost200ResponseFromJSON(json: any): ExplainDefaultPost200Response {
    return ExplainDefaultPost200ResponseFromJSONTyped(json, false);
}

export function ExplainDefaultPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExplainDefaultPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'explanation': json['explanation'],
    };
}

export function ExplainDefaultPost200ResponseToJSON(json: any): ExplainDefaultPost200Response {
    return ExplainDefaultPost200ResponseToJSONTyped(json, false);
}

export function ExplainDefaultPost200ResponseToJSONTyped(value?: ExplainDefaultPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'explanation': value['explanation'],
    };
}

