/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - AutoInterp Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An activation record containing tokens and their corresponding activation values
 * @export
 * @interface NPActivation
 */
export interface NPActivation {
    /**
     * List of tokens for this text
     * @type {Array<string>}
     * @memberof NPActivation
     */
    tokens: Array<string>;
    /**
     * Activation values corresponding to each token
     * @type {Array<number>}
     * @memberof NPActivation
     */
    values: Array<number>;
}

/**
 * Check if a given object implements the NPActivation interface.
 */
export function instanceOfNPActivation(value: object): value is NPActivation {
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function NPActivationFromJSON(json: any): NPActivation {
    return NPActivationFromJSONTyped(json, false);
}

export function NPActivationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NPActivation {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': json['tokens'],
        'values': json['values'],
    };
}

export function NPActivationToJSON(json: any): NPActivation {
    return NPActivationToJSONTyped(json, false);
}

export function NPActivationToJSONTyped(value?: NPActivation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': value['tokens'],
        'values': value['values'],
    };
}

