/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - AutoInterp Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreEmbeddingPost200ResponseBreakdownInner } from './ScoreEmbeddingPost200ResponseBreakdownInner';
import {
    ScoreEmbeddingPost200ResponseBreakdownInnerFromJSON,
    ScoreEmbeddingPost200ResponseBreakdownInnerFromJSONTyped,
    ScoreEmbeddingPost200ResponseBreakdownInnerToJSON,
    ScoreEmbeddingPost200ResponseBreakdownInnerToJSONTyped,
} from './ScoreEmbeddingPost200ResponseBreakdownInner';

/**
 * 
 * @export
 * @interface ScoreEmbeddingPost200Response
 */
export interface ScoreEmbeddingPost200Response {
    /**
     * The score from 0 to 1
     * @type {number}
     * @memberof ScoreEmbeddingPost200Response
     */
    score: number;
    /**
     * Detailed breakdown of the embedding outputs
     * @type {Array<ScoreEmbeddingPost200ResponseBreakdownInner>}
     * @memberof ScoreEmbeddingPost200Response
     */
    breakdown: Array<ScoreEmbeddingPost200ResponseBreakdownInner>;
}

/**
 * Check if a given object implements the ScoreEmbeddingPost200Response interface.
 */
export function instanceOfScoreEmbeddingPost200Response(value: object): value is ScoreEmbeddingPost200Response {
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('breakdown' in value) || value['breakdown'] === undefined) return false;
    return true;
}

export function ScoreEmbeddingPost200ResponseFromJSON(json: any): ScoreEmbeddingPost200Response {
    return ScoreEmbeddingPost200ResponseFromJSONTyped(json, false);
}

export function ScoreEmbeddingPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreEmbeddingPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
        'breakdown': ((json['breakdown'] as Array<any>).map(ScoreEmbeddingPost200ResponseBreakdownInnerFromJSON)),
    };
}

export function ScoreEmbeddingPost200ResponseToJSON(json: any): ScoreEmbeddingPost200Response {
    return ScoreEmbeddingPost200ResponseToJSONTyped(json, false);
}

export function ScoreEmbeddingPost200ResponseToJSONTyped(value?: ScoreEmbeddingPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'breakdown': ((value['breakdown'] as Array<any>).map(ScoreEmbeddingPost200ResponseBreakdownInnerToJSON)),
    };
}

