/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - AutoInterp Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreFuzzDetectionPost200ResponseBreakdownInner } from './ScoreFuzzDetectionPost200ResponseBreakdownInner';
import {
    ScoreFuzzDetectionPost200ResponseBreakdownInnerFromJSON,
    ScoreFuzzDetectionPost200ResponseBreakdownInnerFromJSONTyped,
    ScoreFuzzDetectionPost200ResponseBreakdownInnerToJSON,
    ScoreFuzzDetectionPost200ResponseBreakdownInnerToJSONTyped,
} from './ScoreFuzzDetectionPost200ResponseBreakdownInner';

/**
 * 
 * @export
 * @interface ScoreFuzzDetectionPost200Response
 */
export interface ScoreFuzzDetectionPost200Response {
    /**
     * The score from 0 to 1
     * @type {number}
     * @memberof ScoreFuzzDetectionPost200Response
     */
    score: number;
    /**
     * 
     * @type {Array<ScoreFuzzDetectionPost200ResponseBreakdownInner>}
     * @memberof ScoreFuzzDetectionPost200Response
     */
    breakdown: Array<ScoreFuzzDetectionPost200ResponseBreakdownInner>;
}

/**
 * Check if a given object implements the ScoreFuzzDetectionPost200Response interface.
 */
export function instanceOfScoreFuzzDetectionPost200Response(value: object): value is ScoreFuzzDetectionPost200Response {
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('breakdown' in value) || value['breakdown'] === undefined) return false;
    return true;
}

export function ScoreFuzzDetectionPost200ResponseFromJSON(json: any): ScoreFuzzDetectionPost200Response {
    return ScoreFuzzDetectionPost200ResponseFromJSONTyped(json, false);
}

export function ScoreFuzzDetectionPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreFuzzDetectionPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
        'breakdown': ((json['breakdown'] as Array<any>).map(ScoreFuzzDetectionPost200ResponseBreakdownInnerFromJSON)),
    };
}

export function ScoreFuzzDetectionPost200ResponseToJSON(json: any): ScoreFuzzDetectionPost200Response {
    return ScoreFuzzDetectionPost200ResponseToJSONTyped(json, false);
}

export function ScoreFuzzDetectionPost200ResponseToJSONTyped(value?: ScoreFuzzDetectionPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'breakdown': ((value['breakdown'] as Array<any>).map(ScoreFuzzDetectionPost200ResponseBreakdownInnerToJSON)),
    };
}

