export const INFERENCE_EXAMPLE_TEXTS_CATEGORIZED: { type: string; examples: string[] }[] = [
  {
    type: '🌮 Food',
    examples: [
      'The chocolate lava cake at La Petite Boulangerie is a delight, oozing with rich, molten chocolate as soon as you break into its perfectly baked exterior.',
      'Avocado toast, a simple yet trendy breakfast option, gains a delightful twist with a sprinkle of chili flakes and a drizzle of honey for that perfect balance of spicy and sweet.',
      "Chef Ramirez's signature dish, a fusion of Thai and Mexican cuisine, features spicy green curry enchiladas, tantalizing the taste buds with a bold, innovative flavor combination.",
      'Did you know that pineapples were a symbol of hospitality in colonial America? This exotic fruit, once a rare delicacy, was often displayed at gatherings to impress guests.',
      "The Farmers' Market Salad at Green Acres Café, with its fresh, locally-sourced ingredients and homemade vinaigrette, is a true celebration of seasonal flavors.",
      'A culinary secret: soaking chicken in buttermilk for at least an hour before frying ensures a juicy, tender inside and a perfectly crispy exterior.',
      "At Tokyo's Sushi Zen, the chef's mastery is evident in the simple yet sublime salmon nigiri, where the freshness of the fish is the star of the show.",
      'In the heart of Tuscany, a family-owned vineyard pairs its robust Chianti with a hearty wild boar ragù, creating an unforgettable taste of Italian countryside cuisine.',
      "Exploring the streets of Bangkok, one must try the street vendor's mango sticky rice, a delightful dessert that perfectly balances sweet and savory with creamy coconut milk.",
      'The humble potato, a staple in diets around the world, was once considered so strange and feared in Europe that it was initially used only as animal feed and decoration.',
    ],
  },
  {
    type: '📰 News',
    examples: [
      'In a landmark decision, the Supreme Court has ruled in favor of expanding environmental protections, setting a new legal standard for future legislation and sparking nationwide discussions on environmental policy.',
      'The recent volcanic eruption has caused significant disruptions, prompting urgent evacuations and international aid efforts. Scientists warn of potential long-term ecological and economic impacts.',
      "In an exclusive interview, the newly elected mayor shares her vision for the city's future, focusing on sustainable development, public transportation improvements, and increased affordable housing.",
      'The tech industry faces a major shift as the leading company announces significant layoffs amidst economic downturns. Analysts predict this could have a ripple effect across the global market.',
      'A groundbreaking medical study reveals a potential cure for a rare disease, offering hope to thousands of patients worldwide. The discovery marks a significant milestone in medical research and treatment.',
      'The international sports event concluded with a stunning victory, shattering records and capturing the hearts of fans around the world. The event highlighted the power of sports in uniting diverse cultures.',
      "A major cybersecurity breach has compromised millions of users' data, raising questions about digital security and privacy in the age of information. Experts urge stronger safeguards and consumer awareness.",
      "The art world is abuzz as a long-lost masterpiece is discovered, shedding new light on the artist's work and era. This discovery has sparked renewed interest in the history and value of classic art.",
      'Amidst economic challenges, the government unveils a stimulus package aimed at boosting growth and supporting vulnerable sectors. The plan includes tax relief, small business support, and infrastructure projects.',
      'The festival celebrated cultural diversity through music, dance, and food, drawing thousands of attendees and promoting cross-cultural understanding. It showcased the rich tapestry of traditions in our global society.',
    ],
  },
  {
    type: '📖 Literary',
    examples: [
      "In 'Pride and Prejudice', Elizabeth Bennet's sharp wit and independent spirit challenge the social norms of her time, as she navigates the complexities of love, family, and societal expectations in early 19th-century England.",
      "The narrative of 'Moby-Dick' delves deep into the human psyche through Captain Ahab's obsessive quest for the white whale, symbolizing the eternal struggle between man and nature, and man's pursuit of the unattainable.",
      "'To Kill a Mockingbird' by Harper Lee poignantly addresses themes of racial injustice and moral growth, as seen through the eyes of young Scout Finch, in a small Southern town during the Great Depression.",
      "F. Scott Fitzgerald's 'The Great Gatsby' elegantly captures the disillusionment of the American Dream in the Roaring Twenties, through the tragic story of Jay Gatsby and his unrequited love for Daisy Buchanan.",
      "George Orwell's '1984' presents a chilling dystopian world where government surveillance and public manipulation create a society marked by fear, conformity, and the loss of individuality.",
      "In 'The Catcher in the Rye', J.D. Salinger portrays the complexities of teenage angst and rebellion through the eyes of Holden Caulfield, as he navigates the challenges of adulthood and identity.",
      "'Hamlet' by William Shakespeare masterfully explores themes of betrayal, revenge, and madness, as Prince Hamlet is consumed by the need to avenge his father's murder in a corrupt and decaying kingdom.",
      "Leo Tolstoy's 'War and Peace' offers a sweeping narrative that intertwines the lives of its characters with the tumultuous events of the Napoleonic Wars, reflecting on the broader human experiences of love, loss, and destiny.",
      "In 'The Odyssey', Homer takes us on an epic journey with Odysseus, whose adventures and trials on his way back to Ithaca after the Trojan War offer timeless insights into the human condition and the quest for home.",
      "Charles Dickens' 'Great Expectations' skillfully weaves a tale of personal growth and societal critique, as young Pip's journey from humble beginnings to the complexities of London society reveals the illusions of wealth and class.",
    ],
  },
  {
    type: '👯 Personal',
    examples: [
      "Hey there! Just wanted to check in and see how you're doing. It's been a while since we last caught up. Hope everything is going well with you. Are you still at the same job, or have you moved on to something new?",
      "Can't believe it's already been a year since our last trip! Time flies. We should definitely plan another getaway soon. What do you think? Maybe something tropical or perhaps a city break somewhere we've never been?",
      "Happy Birthday! Hope your day is filled with lots of love, laughter, and cake. Wishing you all the best on your special day. Let's get together soon for a proper celebration with all our friends!",
      "I'm so proud of you and everything you've achieved this year. You've worked so hard, and it's great to see your efforts paying off. Keep chasing your dreams - you're doing amazing!",
      'Just saw the funniest meme and thought of you. It reminded me of that time we... [continues with a personal anecdote]... Do you remember how hard we laughed back then? Good times!',
      "OMG, did you see the latest episode of our favorite show? Can't believe that twist at the end! I need to know what happens next. Let's watch the next one together and have a movie night.",
      "Had the most amazing coffee this morning at that new cafe downtown. You'd love it. Let's catch up there soon! It has this cozy vibe and the pastries are to die for. What do you say?",
      "Remember how we used to dream about traveling the world? Let's start planning our next adventure. We could make a list of all the places we want to visit and start ticking them off.",
      "Feeling so grateful for our friendship. You've been there for me through thick and thin. Thank you for everything. Can't imagine what I would do without you.",
      "Was just reminiscing about our college days. We've come so far since then. Let's plan a reunion soon! It would be amazing to catch up with everyone and see where life has taken us all.",
    ],
  },
  {
    type: '🧑‍💻 Programming',
    examples: [
      'function calculateSum(a, b) { return a + b; } // A simple function to add two numbers. It takes two parameters and returns their sum, which is a fundamental operation in programming.',
      "let user = { name: 'Alice', age: 25 }; // Creating an object in JavaScript. This is a basic example of object creation, where 'user' is an object with properties 'name' and 'age'.",
      "#include <iostream> using namespace std; int main() { cout << 'Hello, world!'; return 0; } // Basic C++ program. This is a classic example of a beginner's program in C++.",
      'SELECT * FROM users WHERE age > 18; // SQL query to select users over 18 years old. This is a simple database query to retrieve information from a table based on a condition.',
      "if (temperature > 100) { alert('High temperature!'); } // Conditional statement in JavaScript. This code checks if the temperature exceeds 100 and displays a warning if it does.",
      'for (int i = 0; i < 10; i++) { console.log(i); } // Looping in JavaScript. This loop prints numbers from 0 to 9, demonstrating a basic for loop structure.',
      "class Car { constructor(brand) { this.carname = brand; } } // Class definition in JavaScript. This snippet defines a class 'Car' with a constructor that assigns a brand name to each instance.",
      "<div class='container'>Hello World!</div> // Basic HTML structure. This is an example of a simple HTML element with a class, often used in web development.",
      'Array.prototype.map = function(callback) { // ... }; // Extending an array in JavaScript. This method creates a new array populated with the results of calling a provided function on every element.',
      "document.getElementById('myElement').style.display = 'none'; // Manipulating DOM in JavaScript. This line of code selects an HTML element and changes its display style, often used in web interactivity.",
    ],
  },
  {
    type: '🧑‍🔬 Technical',
    examples: [
      'This user manual provides step-by-step instructions for operating the device, including safety precautions, troubleshooting tips, and maintenance guidelines. It is essential for ensuring proper use and longevity.',
      'Our feasibility study assesses the viability of the proposed project, analyzing market trends, financial projections, and potential risks. This comprehensive evaluation is crucial for informed decision-making.',
      'The research paper explores the effects of climate change on marine ecosystems, presenting data collected over a decade. It contributes valuable insights to the ongoing discourse on environmental conservation.',
      'This technical report outlines the results of the engineering assessment, detailing structural integrity, design considerations, and recommendations for improvements to meet industry standards.',
      'The policy brief highlights key issues in urban transportation planning, offering evidence-based recommendations for reducing traffic congestion and improving public transit systems in metropolitan areas.',
      'Our white paper discusses the emerging trends in renewable energy technology, examining the potential impact on global energy markets and sustainability goals. It serves as a resource for policymakers and industry leaders.',
      'This project proposal outlines the objectives, scope, timeline, and budget for the new initiative. It serves as a roadmap for execution and is essential for securing stakeholder approval and funding.',
      'The compliance report verifies adherence to regulatory standards, documenting audits, inspections, and corrective actions taken. It is vital for maintaining legal and ethical practices within the organization.',
      'Our training manual provides comprehensive guidance for new employees, covering company policies, job responsibilities, and professional development opportunities. It is a key tool for onboarding and staff development.',
      "The annual report summarizes the company's performance over the past year, including financial highlights, achievements, and future goals. It provides transparency and accountability to stakeholders.",
    ],
  },
  {
    type: '🧑‍🏫 Academic',
    examples: [
      'The study explores the implications of quantum computing on current encryption methods, highlighting the potential for both advancements in computing power and challenges in cybersecurity. The paper argues that quantum computing will necessitate a paradigm shift in data protection.',
      'This article examines the social impacts of the gig economy, particularly focusing on the changing nature of employment and worker rights. It draws on case studies and statistical analysis to argue for policy reform in labor laws.',
      'In exploring the relationship between climate change and urban planning, the research identifies key strategies for sustainable development. It underscores the urgency of integrating environmental considerations into city planning.',
      "The thesis presents an analysis of Shakespeare's use of irony in 'Macbeth', exploring how it contributes to the play's themes of ambition and fate. The study offers a new perspective on the interpretation of these literary elements.",
      'This dissertation investigates the historical context of the French Revolution, providing a nuanced understanding of the political, social, and economic factors that led to this pivotal event in European history.',
      'The journal article delves into the advancements in gene editing technology, specifically CRISPR-Cas9, and its ethical implications. It discusses the potential applications in medicine and the moral considerations involved.',
      'Exploring the concept of artificial intelligence in the workplace, this paper examines its impact on productivity and employee dynamics. It provides a comprehensive overview of AI integration in various industries.',
      'The research on renewable energy technologies assesses their viability as sustainable alternatives to fossil fuels. The study provides a critical analysis of solar, wind, and hydroelectric power in the context of global energy needs.',
      'This scholarly article analyzes the role of social media in modern political discourse, examining its influence on public opinion and election outcomes. It presents a detailed study of social media trends and voter behavior.',
      'Focusing on the cultural significance of mythology in ancient civilizations, the paper explores how myths shaped societal norms, religious beliefs, and artistic expressions. It draws comparisons across various cultures to highlight common themes and differences.',
    ],
  },
  {
    type: '💼 Business',
    examples: [
      'Our quarterly sales report indicates a significant increase in revenue, suggesting our new marketing strategies are paying off. Continued investment in digital advertising is recommended to maintain this growth trajectory.',
      'The strategic merger between the two leading tech companies will create a synergy that promises to revolutionize the industry. This collaboration is expected to yield innovative products and enhanced services.',
      'Effective immediately, all employees are encouraged to participate in our new remote work program. This initiative aims to improve work-life balance and enhance productivity across all departments.',
      "Our customer satisfaction scores have improved by 15% this quarter, a testament to our team's dedication to providing exceptional service. Ongoing training and development will ensure we continue this positive trend.",
      'The launch of our latest product line exceeded expectations, with initial sales surpassing projections by 25%. This success underscores the importance of our customer-focused approach in product development.',
      'To stay competitive in the global market, our company will be investing in cutting-edge technology to streamline operations. This technological advancement will position us at the forefront of industry innovation.',
      'Our comprehensive marketing plan for the upcoming year focuses on expanding our digital presence and engaging with younger demographics through social media platforms and influencer partnerships.',
      'In response to recent market fluctuations, we are adjusting our investment strategies to prioritize long-term stability and sustainable growth. This shift will better align with our overall financial goals.',
      "The annual shareholders' meeting will discuss the company's performance, future strategies, and the appointment of new board members. Shareholder engagement and input are crucial for our continued success.",
      "Our new sustainability initiative aims to reduce the company's carbon footprint by 30% over the next five years. This commitment to environmental responsibility will also enhance our brand reputation.",
    ],
  },
  {
    type: '🧑‍⚖️ Legal',
    examples: [
      'This agreement, entered into on this day, establishes the terms and conditions of the partnership between the parties. It outlines the responsibilities, profit-sharing ratios, and dispute resolution mechanisms.',
      'The proposed legislation aims to enhance public health safety by implementing stricter regulations on food labeling and quality control. Public comments on the bill are encouraged and will be considered.',
      'This court ruling sets a precedent in corporate law, emphasizing the importance of ethical business practices and accountability in financial dealings. The decision underscores the need for transparent corporate governance.',
      "The new zoning laws will affect residential and commercial development, aiming to balance urban growth with environmental conservation. These regulations are part of the city's long-term urban planning strategy.",
      'Under the terms of this contract, the service provider agrees to deliver the specified services within the agreed-upon timeframe. Failure to comply will result in penalties as outlined in the agreement.',
      'This patent grants the inventor exclusive rights to the use, production, and sale of the invention for a period of twenty years, fostering innovation and protecting intellectual property rights.',
      'The privacy policy has been updated to comply with new data protection regulations. It outlines how personal data is collected, used, and safeguarded, reflecting our commitment to user privacy.',
      "This ordinance prohibits parking in designated areas during specific hours to facilitate street cleaning and maintenance. Violations will result in fines and possible towing at the vehicle owner's expense.",
      "The government's budget proposal allocates funds for public infrastructure projects, education, healthcare, and national defense. It reflects priorities for the fiscal year and aims to address key societal needs.",
      'This employment agreement outlines the terms of employment, including job responsibilities, salary, benefits, and conditions for termination. It serves as a binding legal document between the employer and employee.',
    ],
  },
  {
    type: '🧑‍🏫 Educational',
    examples: [
      'To solve a quadratic equation, use the formula: x = (-b ± √(b²-4ac)) / 2a. This formula is derived from the general form ax² + bx + c = 0 and is fundamental in algebra.',
      'Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods from carbon dioxide and water. This process is crucial for life on Earth.',
      'The French Revolution, beginning in 1789, was a period of radical social and political upheaval in France that had a lasting impact on French history and fundamentally transformed French society.',
      'In economics, supply and demand is a model for understanding how prices and quantities are determined in a market system. This concept is foundational in economic theory and affects various market structures.',
      'The human circulatory system consists of the heart, blood vessels, and blood, and is responsible for transporting nutrients and oxygen to the body cells. This system is vital for maintaining life and health.',
      'Mitosis is a process of cell division that results in two genetically identical daughter cells developing from a single parent cell. This process is key to growth and tissue repair in multicellular organisms.',
      'The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse is equal to the sum of the squares of the other two sides. This theorem is a cornerstone of geometry.',
      'During the Industrial Revolution, there was a major shift from manual labor and agrarian economies to industrial and machine manufacturing processes. This period marked a significant change in history.',
      'In literature, a metaphor is a figure of speech that describes an object or action in a way that isn’t literally true, but helps explain an idea or make a comparison. Metaphors enrich language and thought.',
      'The water cycle describes the continuous movement of water on, above, and below the surface of the Earth, involving processes such as evaporation, condensation, and precipitation. This cycle is vital for life.',
    ],
  },
  {
    type: '🗼 Cultural',
    examples: [
      'The Declaration of Independence, adopted on July 4, 1776, stated that the thirteen American colonies were free and independent states. This document is a pivotal moment in American history.',
      "'All men are created equal, that they are endowed by their Creator with certain unalienable Rights.' - from the United States Declaration of Independence. This line is a cornerstone of American democracy.",
      "In his 'I Have a Dream' speech, Martin Luther King Jr. envisioned a future where people would be judged by their character, not the color of their skin. This speech is iconic in the civil rights movement.",
      'The Magna Carta, signed in 1215, was a significant early step in the process of constitutional development in England. It laid the groundwork for the development of parliamentary democracy.',
      "'To be, or not to be, that is the question.' - from Shakespeare's Hamlet, reflecting on life and death. This famous line explores the essence of human existence and philosophical thought.",
      'The Rosetta Stone, discovered in 1799, was crucial in deciphering Egyptian hieroglyphs, a script made up of small pictures. This discovery opened a window into ancient Egyptian civilization.',
      'The Emancipation Proclamation, issued by Abraham Lincoln in 1863, declared that all slaves in Confederate states were to be set free. This was a turning point in the American Civil War.',
      'The Code of Hammurabi is one of the oldest deciphered writings of significant length in the world, dating back to 1754 BC in ancient Mesopotamia. It is a cornerstone of ancient law and governance.',
      'The Treaty of Versailles, signed in 1919, ended the state of war between Germany and the Allied Powers after World War I. It reshaped the map of Europe and had lasting geopolitical consequences.',
      "'Give me liberty, or give me death!' - a famous quotation attributed to Patrick Henry from a speech he made to the Second Virginia Convention in 1775. This phrase became a rallying cry for American independence.",
    ],
  },
];

export const INFERENCE_EXAMPLE_TEXTS: string[] = INFERENCE_EXAMPLE_TEXTS_CATEGORIZED.map((e) => e.examples).flat();
