# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ActivationAllPost200ResponseActivationsInner(BaseModel):
    """
    One feature and its activation in an NPActivationAllResponse
    """ # noqa: E501
    source: StrictStr
    index: StrictInt
    values: List[Union[StrictFloat, StrictInt]]
    sum_values: Optional[Union[StrictFloat, StrictInt]] = None
    max_value: Union[StrictFloat, StrictInt]
    max_value_index: Union[StrictFloat, StrictInt]
    dfa_values: Optional[List[Union[StrictFloat, StrictInt]]] = None
    dfa_target_index: Optional[StrictInt] = None
    dfa_max_value: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["source", "index", "values", "sum_values", "max_value", "max_value_index", "dfa_values", "dfa_target_index", "dfa_max_value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActivationAllPost200ResponseActivationsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActivationAllPost200ResponseActivationsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "index": obj.get("index"),
            "values": obj.get("values"),
            "sum_values": obj.get("sum_values"),
            "max_value": obj.get("max_value"),
            "max_value_index": obj.get("max_value_index"),
            "dfa_values": obj.get("dfa_values"),
            "dfa_target_index": obj.get("dfa_target_index"),
            "dfa_max_value": obj.get("dfa_max_value")
        })
        return _obj


