# coding: utf-8

"""
    Neuronpedia - AutoInterp Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_autointerp_client.models.explain_default_post200_response import ExplainDefaultPost200Response

class TestExplainDefaultPost200Response(unittest.TestCase):
    """ExplainDefaultPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExplainDefaultPost200Response:
        """Test ExplainDefaultPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExplainDefaultPost200Response`
        """
        model = ExplainDefaultPost200Response()
        if include_optional:
            return ExplainDefaultPost200Response(
                explanation = ''
            )
        else:
            return ExplainDefaultPost200Response(
                explanation = '',
        )
        """

    def testExplainDefaultPost200Response(self):
        """Test ExplainDefaultPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
