# coding: utf-8

"""
    Neuronpedia - AutoInterp Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_autointerp_client.models.np_activation import NPActivation

class TestNPActivation(unittest.TestCase):
    """NPActivation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NPActivation:
        """Test NPActivation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NPActivation`
        """
        model = NPActivation()
        if include_optional:
            return NPActivation(
                tokens = ["The","cat","sat"],
                values = [0.5,0.8,0.2]
            )
        else:
            return NPActivation(
                tokens = ["The","cat","sat"],
                values = [0.5,0.8,0.2],
        )
        """

    def testNPActivation(self):
        """Test NPActivation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
