# coding: utf-8

"""
    Neuronpedia - AutoInterp Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_autointerp_client.models.score_embedding_post200_response import ScoreEmbeddingPost200Response

class TestScoreEmbeddingPost200Response(unittest.TestCase):
    """ScoreEmbeddingPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScoreEmbeddingPost200Response:
        """Test ScoreEmbeddingPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScoreEmbeddingPost200Response`
        """
        model = ScoreEmbeddingPost200Response()
        if include_optional:
            return ScoreEmbeddingPost200Response(
                score = 1.337,
                breakdown = [
                    neuronpedia_autointerp_client.models._score_embedding_post_200_response_breakdown_inner._score_embedding_post_200_response_breakdown_inner(
                        text = '', 
                        distance = 56, 
                        similarity = 1.337, )
                    ]
            )
        else:
            return ScoreEmbeddingPost200Response(
                score = 1.337,
                breakdown = [
                    neuronpedia_autointerp_client.models._score_embedding_post_200_response_breakdown_inner._score_embedding_post_200_response_breakdown_inner(
                        text = '', 
                        distance = 56, 
                        similarity = 1.337, )
                    ],
        )
        """

    def testScoreEmbeddingPost200Response(self):
        """Test ScoreEmbeddingPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
