# coding: utf-8

"""
    Neuronpedia - AutoInterp Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NPScoreFuzzDetectionType(str, Enum):
    """
    Type of scoring method, either fuzz or detection
    """

    """
    allowed enum values
    """
    FUZZ = 'FUZZ'
    DETECTION = 'DETECTION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NPScoreFuzzDetectionType from a JSON string"""
        return cls(json.loads(json_str))


