# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.tokenize_post200_response import TokenizePost200Response

class TestTokenizePost200Response(unittest.TestCase):
    """TokenizePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizePost200Response:
        """Test TokenizePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizePost200Response`
        """
        model = TokenizePost200Response()
        if include_optional:
            return TokenizePost200Response(
                tokens = [
                    56
                    ],
                token_strings = [
                    ''
                    ],
                prepend_bos = True
            )
        else:
            return TokenizePost200Response(
                tokens = [
                    56
                    ],
                token_strings = [
                    ''
                    ],
                prepend_bos = True,
        )
        """

    def testTokenizePost200Response(self):
        """Test TokenizePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
