# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.util_sae_vector_post_request import UtilSaeVectorPostRequest

class TestUtilSaeVectorPostRequest(unittest.TestCase):
    """UtilSaeVectorPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UtilSaeVectorPostRequest:
        """Test UtilSaeVectorPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UtilSaeVectorPostRequest`
        """
        model = UtilSaeVectorPostRequest()
        if include_optional:
            return UtilSaeVectorPostRequest(
                model = 'gpt2-small',
                source = '0-res-jb',
                index = 14057
            )
        else:
            return UtilSaeVectorPostRequest(
                model = 'gpt2-small',
                source = '0-res-jb',
                index = 14057,
        )
        """

    def testUtilSaeVectorPostRequest(self):
        """Test UtilSaeVectorPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
