# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.steer_completion_post200_response import SteerCompletionPost200Response

class TestSteerCompletionPost200Response(unittest.TestCase):
    """SteerCompletionPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SteerCompletionPost200Response:
        """Test SteerCompletionPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SteerCompletionPost200Response`
        """
        model = SteerCompletionPost200Response()
        if include_optional:
            return SteerCompletionPost200Response(
                outputs = [
                    neuronpedia_inference_client.models.np_steer_completion_response_inner.NPSteerCompletionResponseInner(
                        type = 'STEERED', 
                        output = '', )
                    ]
            )
        else:
            return SteerCompletionPost200Response(
                outputs = [
                    neuronpedia_inference_client.models.np_steer_completion_response_inner.NPSteerCompletionResponseInner(
                        type = 'STEERED', 
                        output = '', )
                    ],
        )
        """

    def testSteerCompletionPost200Response(self):
        """Test SteerCompletionPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
