# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.activation_all_post_request import ActivationAllPostRequest

class TestActivationAllPostRequest(unittest.TestCase):
    """ActivationAllPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivationAllPostRequest:
        """Test ActivationAllPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivationAllPostRequest`
        """
        model = ActivationAllPostRequest()
        if include_optional:
            return ActivationAllPostRequest(
                prompt = '',
                model = '',
                source_set = '',
                selected_sources = [
                    ''
                    ],
                sort_by_token_indexes = [
                    56
                    ],
                ignore_bos = True,
                feature_filter = [
                    56
                    ],
                num_results = 56
            )
        else:
            return ActivationAllPostRequest(
                prompt = '',
                model = '',
                source_set = '',
                selected_sources = [
                    ''
                    ],
                sort_by_token_indexes = [
                    56
                    ],
                ignore_bos = True,
        )
        """

    def testActivationAllPostRequest(self):
        """Test ActivationAllPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
