# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.tokenize_post_request import TokenizePostRequest

class TestTokenizePostRequest(unittest.TestCase):
    """TokenizePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizePostRequest:
        """Test TokenizePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizePostRequest`
        """
        model = TokenizePostRequest()
        if include_optional:
            return TokenizePostRequest(
                model = 'gpt2-small',
                text = 'tokenize me! :D',
                prepend_bos = True
            )
        else:
            return TokenizePostRequest(
                model = 'gpt2-small',
                text = 'tokenize me! :D',
        )
        """

    def testTokenizePostRequest(self):
        """Test TokenizePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
