# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.activation_single_post_request import ActivationSinglePostRequest

class TestActivationSinglePostRequest(unittest.TestCase):
    """ActivationSinglePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivationSinglePostRequest:
        """Test ActivationSinglePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivationSinglePostRequest`
        """
        model = ActivationSinglePostRequest()
        if include_optional:
            return ActivationSinglePostRequest(
                prompt = '',
                model = '',
                source = '',
                index = '',
                vector = [
                    1.337
                    ],
                hook = ''
            )
        else:
            return ActivationSinglePostRequest(
                prompt = '',
                model = '',
        )
        """

    def testActivationSinglePostRequest(self):
        """Test ActivationSinglePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
