# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.np_feature import NPFeature

class TestNPFeature(unittest.TestCase):
    """NPFeature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NPFeature:
        """Test NPFeature
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NPFeature`
        """
        model = NPFeature()
        if include_optional:
            return NPFeature(
                model = 'gpt2-small',
                source = '0-res-jb',
                index = 14057
            )
        else:
            return NPFeature(
                model = 'gpt2-small',
                source = '0-res-jb',
                index = 14057,
        )
        """

    def testNPFeature(self):
        """Test NPFeature"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
