# coding: utf-8

"""
    Neuronpedia - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@neuronpedia.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neuronpedia_inference_client.models.util_sae_topk_by_decoder_cossim_post200_response import UtilSaeTopkByDecoderCossimPost200Response

class TestUtilSaeTopkByDecoderCossimPost200Response(unittest.TestCase):
    """UtilSaeTopkByDecoderCossimPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UtilSaeTopkByDecoderCossimPost200Response:
        """Test UtilSaeTopkByDecoderCossimPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UtilSaeTopkByDecoderCossimPost200Response`
        """
        model = UtilSaeTopkByDecoderCossimPost200Response()
        if include_optional:
            return UtilSaeTopkByDecoderCossimPost200Response(
                feature = neuronpedia_inference_client.models.np_feature.NPFeature(
                    model = 'gpt2-small', 
                    source = '0-res-jb', 
                    index = 14057, ),
                topk_decoder_cossim_features = [
                    neuronpedia_inference_client.models._util_sae_topk_by_decoder_cossim_post_200_response_topk_decoder_cossim_features_inner._util_sae_topk_by_decoder_cossim_post_200_response_topk_decoder_cossim_features_inner(
                        feature = neuronpedia_inference_client.models.np_feature.NPFeature(
                            model = 'gpt2-small', 
                            source = '0-res-jb', 
                            index = 14057, ), 
                        cosine_similarity = 1.337, )
                    ]
            )
        else:
            return UtilSaeTopkByDecoderCossimPost200Response(
        )
        """

    def testUtilSaeTopkByDecoderCossimPost200Response(self):
        """Test UtilSaeTopkByDecoderCossimPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
